### ISSUE TITLE
[Request]: Support Farmer's Delight Refabricated

### ISSUE THREAD

**Issue by Partonetrain** [Kneelawk/extra-mod-integrations#19]
Farmer's Delight now has a more faithful Fabric port, which Extra Mod Integrations doesn't expect.
```
[21:39:46] [Thread-107/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.kneelawk.extramodintegrations.AbstractFDIntegration
[21:39:46] [Thread-107/INFO]: [STDERR]: 	at com.kneelawk.extramodintegrations.ExMIPlugin.register(ExMIPlugin.java:32)
[21:39:46] [Thread-107/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:183)
[21:39:46] [Thread-107/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:39:46] [Thread-107/INFO]: [STDERR]: Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: com/nhoryzon/mc/farmersdelight/registry/BlocksRegistry [in thread "Thread-38"]
[21:39:46] [Thread-107/INFO]: [STDERR]: 	at com.kneelawk.extramodintegrations.farmersdelight.FDIntegration.<clinit>(FDIntegration.java:21)
[21:39:46] [Thread-107/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName0(Native Method)
[21:39:46] [Thread-107/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName(Class.java:375)
[21:39:46] [Thread-107/INFO]: [STDERR]: 	at com.kneelawk.extramodintegrations.util.ReflectionUtils.newInstance(ReflectionUtils.java:13)
[21:39:46] [Thread-107/INFO]: [STDERR]: 	at com.kneelawk.extramodintegrations.util.ReflectionUtils.newIntegrationInstance(ReflectionUtils.java:21)
[21:39:46] [Thread-107/INFO]: [STDERR]: 	at com.kneelawk.extramodintegrations.AbstractFDIntegration.<clinit>(AbstractFDIntegration.java:15)
[21:39:46] [Thread-107/INFO]: [STDERR]: 	... 3 more
[21:39:46] [Thread-107/ERROR]: [EMI] java.lang.NoClassDefFoundError: Could not initialize class com.kneelawk.extramodintegrations.AbstractFDIntegration
	at com.kneelawk.extramodintegrations.ExMIPlugin.register(ExMIPlugin.java:32)
	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:183)
	at java.base
[21:39:46] [Thread-107/ERROR]: [EMI] java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: com
[21:39:46] [Thread-107/ERROR]: [EMI] nhoryzon
[21:39:46] [Thread-107/ERROR]: [EMI] mc
[21:39:46] [Thread-107/ERROR]: [EMI] farmersdelight
[21:39:46] [Thread-107/ERROR]: [EMI] registry
[21:39:46] [Thread-107/ERROR]: [EMI] BlocksRegistry [in thread "Thread-38"]
	at com.kneelawk.extramodintegrations.farmersdelight.FDIntegration.<clinit>(FDIntegration.java:21)
	at java.base
[21:39:46] [Thread-107/ERROR]: [EMI] java.lang.Class.forName0(Native Method)
	at java.base
[21:39:46] [Thread-107/ERROR]: [EMI] java.lang.Class.forName(Class.java:375)
	at com.kneelawk.extramodintegrations.util.ReflectionUtils.newInstance(ReflectionUtils.java:13)
	at com.kneelawk.extramodintegrations.util.ReflectionUtils.newIntegrationInstance(ReflectionUtils.java:21)
	at com.kneelawk.extramodintegrations.AbstractFDIntegration.<clinit>(AbstractFDIntegration.java:15)
	... 3 more
```

**Comment by Partonetrain** [comment]
EMI is now supported by default in Refabricated (although the logspam could be reduced)
