### ISSUE TITLE
All the other mod support breaks when using Farmer's Delight Refabricated

### ISSUE THREAD

**Issue by aninusmuffin** [Kneelawk/extra-mod-integrations#20]
When using the [new port of Farmer's Delight](https://modrinth.com/mod/farmers-delight-refabricated) the integration crashes. https://github.com/Kneelawk/extra-mod-integrations/issues/19

Refabricated now has built in support for EMI, but the crash still happens and none of the other integrations work.

I think Farmer's Delight Integration should be removed, because [the original fabric port](https://modrinth.com/mod/farmers-delight-fabric) is Deprecated.
```
[21:39:26] [Thread-11/INFO]: [Extra Mod Integrations] Skipping integration for Tech Reborn (mod not found)
[21:39:26] [Thread-11/INFO]: [Extra Mod Integrations] Skipping integration for Industrial Revolution (mod not found)
[21:39:26] [Thread-11/INFO]: [Extra Mod Integrations] Loading Farmer's Delight Integration...
[21:39:26] [Thread-11/ERROR]: [EMI] Exception loading plugin provided by extra-mod-integrations
[21:39:26] [Thread-11/INFO]: [STDERR]: java.lang.NoClassDefFoundError: com/nhoryzon/mc/farmersdelight/registry/RecipeTypesRegistry
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at com.kneelawk.extramodintegrations.farmersdelight.FDIntegration.registerImpl(FDIntegration.java:65)
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at com.kneelawk.extramodintegrations.AbstractFDIntegration.register(AbstractFDIntegration.java:26)
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at com.kneelawk.extramodintegrations.ExMIPlugin.register(ExMIPlugin.java:32)
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:183)
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[21:39:26] [Thread-11/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: com.nhoryzon.mc.farmersdelight.registry.RecipeTypesRegistry
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:175)
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147)
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239)
[21:39:26] [Thread-11/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[21:39:26] [Thread-11/INFO]: [STDERR]: 	... 5 more
[21:39:26] [Thread-11/ERROR]: [EMI] java.lang.NoClassDefFoundError: com
[21:39:26] [Thread-11/ERROR]: [EMI] nhoryzon
[21:39:26] [Thread-11/ERROR]: [EMI] mc
[21:39:26] [Thread-11/ERROR]: [EMI] farmersdelight
[21:39:26] [Thread-11/ERROR]: [EMI] registry
[21:39:26] [Thread-11/ERROR]: [EMI] RecipeTypesRegistry
	at com.kneelawk.extramodintegrations.farmersdelight.FDIntegration.registerImpl(FDIntegration.java:65)
	at com.kneelawk.extramodintegrations.AbstractFDIntegration.register(AbstractFDIntegration.java:26)
	at com.kneelawk.extramodintegrations.ExMIPlugin.register(ExMIPlugin.java:32)
	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:183)
	at java.base
[21:39:26] [Thread-11/ERROR]: [EMI] java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: com.nhoryzon.mc.farmersdelight.registry.RecipeTypesRegistry
	at java.base
[21:39:26] [Thread-11/ERROR]: [EMI] jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base
[21:39:26] [Thread-11/ERROR]: [EMI] jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base
[21:39:26] [Thread-11/ERROR]: [EMI] java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:175)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239)
	at java.base
[21:39:26] [Thread-11/ERROR]: [EMI] java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 5 more
```

**Comment by Abbie5** [comment]
fixed as of v0.4.4+1.20.1
